spring:
  application:
    name: myapp
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weekly-drafts/config-repo-spring-cloud-configserver-vault
  profiles:
    active: default, native, git
server:
  port: 8888