spring:
  application:
    name: myapp
  cloud:
    config:
      server:
        git:
          uri: https://github.com/navuniverse/spring-vault-properties
  profiles:
    active: default, native, git
server:
  port: 8888